project:
  type: website

website:
  title: "Gayeon Yoo"
  page-footer:
    left: |
      Proudly supported by 가연
    center:  
      - text: "Contact"
        href: contact.qmd

    right:
      - icon: github
        href: https://github.com/7ryean
        aria-label: 가연 Github
  navbar:
    search : true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: blog/index.qmd
      - text: "Portfolio"
        file: portfolio/index.qmd
      - contact.qmd
    right:
      - icon: github
        href: https://github.com/7ryean
        aria-label: 가연 Github


format:
  html:
    smooth-scroll: true
    theme:       
      - styles.css
      - custom.scss

    toc: true

editor: visual

